config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'

  resources :contacts, only: :create
  resources :podcasts
  resources :books do
    resources :chapters
  end
  resources :chapters do
    resources :questions
  end
  resources :questions do
    resources :comments, module: :questions
  end
  resources :users do
    resource :profile
    resources :comments
  end
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  get 'podcast', to: 'pages#podcast'
  resources :essays do
    resources :comments, module: :essays, shallow: true
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :chapter
  validates :title, presence: true,
                    length:{minimum: 5}
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Question.find(params[:question_id])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_chapter

  def show
    @question = @chapter.questions.find(params[:id])
  end

  def index
    @chapter = @book.chapters.find(params[:id])
    @questions = @chapter.questions.where(chapter_id: @chapter.id).order("created_at ASC")
  end

  def new
    @question = @chapter.questions.new
  end

  def edit
    @question = @chapter.questions.find(params[:id])
  end

  def create
    @question =  @chapter.questions.new(question_params)
    if @question.save
      redirect_to book_chapter_path(@chapter.book, @chapter)
    else
      render 'new'
    end
  end

  def update
    @question = @chapter.questions.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
    render 'edit'
  end
end

  def destroy
    @question = @chapter.questions.find(params[:id])
    @question.destroy

    redirect_back(fallback_location: root_path)
  end

  private
    def question_params
      params.require(:question).permit(:title)
    end
    def set_chapter
      @chapter = Chapter.find_by(id: params[:chapter_id])
      if @chapter.nil?
        redirect_to books_path
      end
    end
  end

app/views/questions/_form.html.erb
<%= form_for [@chapter, question] do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit "Submit" %>
  </p>
<% end %>

app/views/questions/edit.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col">
    <h3>Edit Question</h3>
  </div>
</div>

<%= render 'form', question: @question %>

<%= link_to 'Back', book_chapter_path %>

app/views/questions/index.html.erb
<div class="homepage">
  <div class="mdl-grid">
    <div class="mdl-layout-spacer"></div>
    <div class="mdl-cell mdl-cell--4-col">
      <h3><%= @chapter.title %></h3>
      <h5><%= @chapter.text %></h5>
    </div>
    <div class="mdl-layout-spacer"></div>
  </div>
  <div class="mdl-grid homepage">
  <% @chapter.questions.each do |question| %>
    <% if current_user && current_user.role == 'admin' %>
      <%= link_to 'Edit Question', edit_chapter_question_path(@chapter, question) %> |
      <%= link_to 'Delete Question', chapter_question_path(@chapter, question),
                method: :delete,
                data: { confirm: 'Are you sure?' } %> |
    <% end %>
    <div class= "mdl-cell mdl-cell--8-col mdl-card mdl-shadow--2dp mdl-cell--8-col-phone ">
      <div class="mdl-card__title mdl-card--expand" style="background-color:#651FFF">
        <h6 class="mdl-card__title-text" style="color:#FFF"><%= question.title %></h6>
        <%= question.text %>
      </div>
      <div class=" mdl-card__supporting-text">
        <%= render 'comments/comment', commentable: question%>
        <hr>
      </div>
      <div class="mdl-card__supporting-text">
        <% if current_user %>
          <%= render 'comments/form', commentable: question%>
        <% else %>
          Comment:
          <%= link_to "Join Us", new_user_registration_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--accent" %>
          <%= link_to "Log In", new_user_session_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--colored" %>
        <% end %>
      </div>
    </div>
  <% end %>
    <% if current_user && current_user.role == 'admin' %>
      <%= render 'questions/form', question: @chapter.questions.new %>
      <%= link_to 'Edit Chapter', edit_book_chapter_path(@book, @chapter) %> |
      <%= link_to 'Destroy Chapter', book_chapter_path(@book, @chapter),
                method: :delete,
                data: { confirm: 'Are you sure?' } %> |
    <% end %>
  </div>
</div>
<i class="material-icons"><%= link_to 'back', book_chapters_path, class: "mdl-button mdl-js-button mdl-button--mini-fab  mdl-button--accent" %></i>

app/views/questions/new.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col">
    <h3>New Question</h3>
  </div>
</div>
<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<div class="homepage">
  <h3><%= @question.title %></h3>
  <h5><%= @question.text %></h5>
  <p>
    <%= link_to 'Edit', edit_question_path(@question) %> |
    <%= link_to 'Destroy', question_path(@question),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Back', questions_path %> |
  </p>
</div>