config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'

  resources :contacts, only: :create
  resources :podcasts
  resources :books do
    resources :chapters
  end
  resources :chapters do
    resources :questions
  end
  resources :questions do
    resources :comments, module: :questions
  end
  resources :users do
    resource :profile
    resources :comments
  end
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  get 'podcast', to: 'pages#podcast'
  resources :essays do
    resources :comments, module: :essays, shallow: true
  end
end

app/models/book.rb
class Book < ApplicationRecord
  #has_many :comments, as: :commentable
  validates :title, presence: true,
                    length:{minimum: 5}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
    @chapters = Chapter.where(book_id: @book.id).order("updated_at ASC")
  end

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book =  Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title,:text,:author)
    end
end

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit "Submit" %>
  </p>
<% end %>

app/views/books/edit.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col"><h3>Edit Book</h3></div>
</div>
<%= render 'form'%>
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="homepage">
  <div class="mdl-grid">
    <div class="mdl-layout-spacer"></div>
    <div class="mdl-cell mdl-cell--4-col"><h3>Book Club</h3></div>
    <div class="mdl-layout-spacer"></div>
  </div>
  <div class="mdl-grid homepage">
  <% @books.each do |book| %>
    <div class="mdl-cell mdl-cell--4-col demo-card-square mdl-card mdl-shadow--2dp mdl-cell--2-col-phone">
      <div class="mdl-card__title mdl-card--expand" style="background-color:#651FFF">
        <h2 class="mdl-card__title-text"><%= book.title%> </h2>
      </div>
      <div class="mdl-card__supporting-text">
        <%= book.text %>
      </div>
      <div class="mdl-card__actions mdl-card--border">
        <%=link_to 'View book',book_path(book), class: "mdl-button mdl-button--colored mdl-js-button"%>
      </div>
    </div>
  <% end %>
  </div>
  <% if current_user && current_user.role == 'admin' %>
    <% @books.each do |book| %>
      <%= link_to 'Edit', edit_book_path(book) %> |
      <%= link_to 'Destroy', book_path(book),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
    <% end %>
    <%= link_to "New", new_book_path%>
  <% end %>
  <br><br><br><br><br>
</div>
<i class="material-icons"><%= link_to 'back', root_path, class: "mdl-button mdl-js-button mdl-button--mini-fab  mdl-button--accent" %></i>

app/views/books/new.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col"><h3>New Book</h3></div>
</div>
<%= render 'form' %>
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="homepage">
  <div class="mdl-grid">
    <div class="mdl-layout-spacer"></div>
    <div class="mdl-cell mdl-cell--4-col">
      <br>
      <br>
      <h3><%= @book.title %></h3>
    </div>
    <div class="mdl-layout-spacer"></div>
  </div>
  <div class="mdl-grid homepage">
    <% @colors = ["purp", "purp1", "purp"] %>
           <% @i = 0 %>
  <% @chapters.each do |chapter| %>
      <div class="mdl-cell mdl-cell--4-col demo-card-square mdl-card mdl-shadow--2dp mdl-cell--2-col-phone">
        <div class="mdl-card__title mdl-card--expand <%= @colors[@i] %>">
          <h2 class="mdl-card__title-text"><%= chapter.title%> </h2>
        </div>
        <div class="mdl-card__supporting-text">
          <%= chapter.text %>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <% if user_signed_in? %>
            <% if current_user.profile %>
              <%=link_to 'View Chapter', book_chapter_path(@book,chapter), class: "mdl-button mdl-button--colored mdl-js-button "%>
            <% else %>
              <%=link_to "Update Profile", new_user_profile_path(user_id: current_user.id), class: "mdl-button mdl-button--colored mdl-js-button "%>
            <% end %>
          <% else %>
            <%= link_to "Join Us", new_user_registration_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--accent" %>
            <%= link_to "Log In", new_user_session_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--colored" %>
          <% end %>
        </div>
      </div>
      <% if @i == @colors.count - 1 %>
         <% @i = 0 %>
      <% end %>
      <% @i += 1 %>
    <% end %>
  </div>
  <p>
    <% if current_user && current_user.role == 'admin' %>
      <%= link_to 'Edit', edit_book_path(@book) %> |
      <%= link_to 'Destroy', book_path(@book),
            method: :delete,
            data: { confirm: 'Are you sure?' } %> |
      <%= link_to 'New chapter', new_book_chapter_path(@book, @chapter) %>
    <% end %>
  </p>
</div>
<i class="material-icons"><%= link_to 'back', books_path, class: "mdl-button mdl-js-button mdl-button--mini-fab  mdl-button--accent" %></i>