config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'

  resources :contacts, only: :create
  resources :podcasts
  resources :books do
    resources :chapters
  end
  resources :chapters do
    resources :questions
  end
  resources :questions do
    resources :comments, module: :questions
  end
  resources :users do
    resource :profile
    resources :comments
  end
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  get 'podcast', to: 'pages#podcast'
  resources :essays do
    resources :comments, module: :essays, shallow: true
  end
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :questions
  belongs_to :book
  validates :title, presence: true,
                    length:{minimum: 5}
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
    before_action :set_book
  def show
    @chapter = @book.chapters.find(params[:id])
    @questions = @chapter.questions.where(chapter_id: @chapter.id).order("created_at ASC")
  end

  def index
    @chapters = Chapter.where(book_id: @book.id).order("updated_at ASC")
  end


  def new
    @chapter = @book.chapters.new
  end

  def edit
    @chapter = @book.chapters.find(params[:id])
  end

  def create
    @chapter = @book.chapters.new(chapter_params)

    if @chapter.save
      render 'books/index'
    else
      render 'books/index'
    end
  end

  def update
    @chapter = @book.chapters.find(params[:id])

    if @chapter.update(chapter_params)
      redirect_to @chapter
    else
      render 'edit'
  end
end

  def destroy
    @chapter = @book.chapters.find(params[:id])
    @chapter.destroy
    redirect_back(fallback_location: root_path)
  end

  private
    def chapter_params
      params.require(:chapter).permit(:title, :text)
    end
    def set_book
      @book = Book.find_by(id: params[:book_id])
      if @book.nil?
        redirect_to books_path
      end
    end
  end

app/views/chapters/_form.html.erb
<%= form_for [@book, @chapter] do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit "Submit" %>
  </p>
<% end %>

app/views/chapters/edit.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col"><h3>Edit Chapter</h3></div>
</div>
<%= render 'form'%>
<%= link_to 'Back', book_path(@book) %>

app/views/chapters/index.html.erb
<div class="homepage">
  <div class="mdl-grid">
    <div class="mdl-layout-spacer"></div>
    <div class="mdl-cell mdl-cell--4-col">
      <h3><%= @book.title %></h3>
    </div>
    <div class="mdl-layout-spacer"></div>
  </div>
  <div class="mdl-grid homepage">
    <% @colors = ["purp", "purp1", "purp"] %>
           <% @i = 0 %>
  <% @chapters.each do |chapter| %>
      <div class="mdl-cell mdl-cell--4-col demo-card-square mdl-card mdl-shadow--2dp mdl-cell--2-col-phone">
        <div class="mdl-card__title mdl-card--expand <%= @colors[@i] %>">
          <h2 class="mdl-card__title-text"><%= chapter.title%> </h2>
        </div>
        <div class="mdl-card__supporting-text">
          <%= chapter.text %>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <% if user_signed_in? %>
            <% if current_user.profile %>
              <%=link_to 'View Chapter', book_chapter_path(@book,chapter), class: "mdl-button mdl-button--colored mdl-js-button "%>
            <% else %>
              <%=link_to "Update Profile", new_user_profile_path(user_id: current_user.id), class: "mdl-button mdl-button--colored mdl-js-button "%>
            <% end %>
          <% else %>
            <%= link_to "Join Us", new_user_registration_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--accent" %>
            <%= link_to "Log In", new_user_session_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--colored" %>
          <% end %>
        </div>
      </div>
      <% if @i == @colors.count - 1 %>
         <% @i = 0 %>
      <% end %>
      <% @i += 1 %>
    <% end %>
  </div>
  <p>
    <% if current_user && current_user.role == 'admin' %>
      <%= link_to 'Edit', edit_book_path(@book) %> |
      <%= link_to 'Destroy', book_path(@book),
            method: :delete,
            data: { confirm: 'Are you sure?' } %> |
      <%= link_to 'New chapter', new_book_chapter_path(@book, @chapter) %>
    <% end %>
  </p>
</div>
<i class="material-icons"><%= link_to 'back', books_path, class: "mdl-button mdl-js-button mdl-button--mini-fab  mdl-button--accent" %></i>

app/views/chapters/new.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col"><h3>New Chapter</h3></div>
</div>
<%= render 'form' %>
<%= link_to 'Back', books_path %>

app/views/chapters/show.html.erb
<div class="homepage">
  <div class="mdl-grid">
    <div class="mdl-layout-spacer"></div>
    <div class="mdl-cell mdl-cell--4-col">
      <h3><%= @chapter.title %></h3>
      <h5><%= @chapter.text %></h5></div>
    <div class="mdl-layout-spacer"></div>
  </div>
  <div class="mdl-grid homepage">
  <% @chapter.questions.each do |question| %>
    <% if current_user && current_user.role == 'admin' %>
      <%= link_to 'Edit Question', edit_chapter_question_path(@chapter, question) %> |
      <%= link_to 'Delete Question', chapter_question_path(@chapter, question),
                method: :delete,
                data: { confirm: 'Are you sure?' } %> |
    <% end %>
    <div class= "mdl-cell mdl-cell--8-col mdl-card mdl-shadow--2dp mdl-cell--8-col-phone ">
      <div class="mdl-card__title mdl-card--expand" style="background-color:#651FFF">
        <h6 class="mdl-card__title-text" style="color:#FFF"><%= question.title %></h6>
        <%= question.text %>
      </div>
      <div class=" mdl-card__supporting-text">
        <%= render 'comments/comment', commentable: question%>
        <hr>
      </div>
      <div class="mdl-card__supporting-text">
        <% if current_user %>
          <%= render 'comments/form', commentable: question%>
        <% else %>
        Comment:
        <%= link_to "Join Us", new_user_registration_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--accent" %>
        <%= link_to "Log In", new_user_session_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--colored" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if current_user && current_user.role == 'admin' %>
    <%= render 'questions/form', question: @chapter.questions.new %>
    <%= link_to 'Edit Chapter', edit_book_chapter_path(@book, @chapter) %> |
    <%= link_to 'Destroy Chapter', book_chapter_path(@book, @chapter),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> |
  <% end %>
  </div>
</div>
<i class="material-icons"><%= link_to 'back', book_chapters_path, class: "mdl-button mdl-js-button mdl-button--mini-fab  mdl-button--accent" %></i>