config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'

  resources :contacts, only: :create
  resources :podcasts
  resources :books do
    resources :chapters
  end
  resources :chapters do
    resources :questions
  end
  resources :questions do
    resources :comments, module: :questions
  end
  resources :users do
    resource :profile
    resources :comments
  end
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  get 'podcast', to: 'pages#podcast'
  resources :essays do
    resources :comments, module: :essays, shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  #has_many :comments, as: :commentable
  validates :title, presence: true,
                    length:{minimum: 5}
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :questions
  belongs_to :book
  validates :title, presence: true,
                    length:{minimum: 5}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/essay.rb
class Essay < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
  validates :title, presence: true,
                    length:{minimum: 5}
end

app/models/mental_model.rb
class MentalModel < ApplicationRecord
  validates :name, :description, presence: true
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  validates :title, presence: true,
                    length:{minimum: 5}
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :chapter
  validates :title, presence: true,
                    length:{minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  before_create :add_role_to_user
  ROLES = %w[admin member].freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  has_many :comments, dependent: :destroy

  def add_role_to_user
    self.role = 'member'
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
    @chapters = Chapter.where(book_id: @book.id).order("updated_at ASC")
  end

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book =  Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title,:text,:author)
    end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
    before_action :set_book
  def show
    @chapter = @book.chapters.find(params[:id])
    @questions = @chapter.questions.where(chapter_id: @chapter.id).order("created_at ASC")
  end

  def index
    @chapters = Chapter.where(book_id: @book.id).order("updated_at ASC")
  end


  def new
    @chapter = @book.chapters.new
  end

  def edit
    @chapter = @book.chapters.find(params[:id])
  end

  def create
    @chapter = @book.chapters.new(chapter_params)

    if @chapter.save
      render 'books/index'
    else
      render 'books/index'
    end
  end

  def update
    @chapter = @book.chapters.find(params[:id])

    if @chapter.update(chapter_params)
      redirect_to @chapter
    else
      render 'edit'
  end
end

  def destroy
    @chapter = @book.chapters.find(params[:id])
    @chapter.destroy
    redirect_back(fallback_location: root_path)
  end

  private
    def chapter_params
      params.require(:chapter).permit(:title, :text)
    end
    def set_book
      @book = Book.find_by(id: params[:book_id])
      if @book.nil?
        redirect_to books_path
      end
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    @comment.update(comment_params)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.user = current_user
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  #GET request to /contact-us
  #Show new contact form
  def new
    @contact = Contact.new
  end

#POST request /contacts
  def create
    #Mass assignment of form fields into Contact object
    @contact = Contact.new(contact_params)
    #Save the Contact object to the database
    if @contact.save
      #Store form fields via parameters, into variables
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      #PLug variables into Contact MMailer
      #email method and send methods
      ContactMailer.contact_email(name, email, body).deliver
      #Store success message in flash hash
      #and redirect to the 'new' action
      flash[:notice] = "Thanks for the suggestion, hopefully we can implement it!"
      redirect_to new_contact_path
    else
      #If Contact object doesn't save, store error message in flash hash
      #and redirect to the 'new' action
      flash[:notice] = @contact.errors.full_messages.join(". ")
      redirect_to new_contact_path
    end
  end

  private
  #To collect data from form we need to use strong parameters and whitelist the form fields
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/essays_controller.rb
class EssaysController < ApplicationController

  def show
    @essay =Essay.find(params[:id])
  end

  def index
    @essays = Essay.all
  end

  def new
    @essay = Essay.new
  end

  def edit
    @essay = Essay.find(params[:id])
  end

  def create
    @essay =  Essay.new(essay_params)

    if @essay.save
      redirect_to @essay
    else
      render 'new'
    end
  end

  def update
    @essay = Essay.find(params[:id])

    if @essay.update(essay_params)
      redirect_to @essay
    else
    render 'edit'
  end
end

  def destroy
    @essay = Essay.find(params[:id])
    @essay.destroy

    redirect_to essays_path
  end

  private
    def essay_params
      params.require(:essay).permit(:title,:text)
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def resources
  end

  def privacy
  end

  def terms
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # GET to /users/:id
  def show
    @user = User.find( params[:id] )
  end

  def index
    @users = User.includes(:profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mental_models_helper.rb
module MentalModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Periculum</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="https://imgur.com/tKpU5dp.png" />
    <meta property="og:description" content="Learning Platform" />
    <meta name="google-site-verification" content="_UeWDyuN-7B6YNGYUlEApavHNQlAwJcRVHT3eKZ3iRg" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span>
            <%= link_to root_path do %>
              <%= image_tag "minilogo.png", class: "mdl-layout-title" %>
            <% end %>
          </span>   <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation. We hide it in small screens. -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <%= link_to 'Book Club', books_path, class: 'mdl-navigation__link'%>
            <%#= link_to 'Essays',  essays_path, class: 'mdl-navigation__link'%>
            <%#= link_to 'Per Talks', podcasts_path, class: 'mdl-navigation__link' %>
            <%#= link_to 'Resources', '/resources', class: 'mdl-navigation__link' %>
            <% if user_signed_in? %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--accent" %>
            <% else %>
              <%= link_to "Join Us", new_user_registration_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--accent" %>
              <%= link_to "Log In", new_user_session_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--colored" %>
            <% end %>
          </nav>
        </div>
      </header>
    </div>
    <div class="mdl-layout__drawer">
      <span class="mdl-layout-title">
        <%= link_to root_path do %>
          <%= image_tag "minilogo.png", class: "mdl-layout-title" %>
        <% end %>
      </span>
      <nav class="mdl-navigation">
        <%= link_to 'Book Club', books_path, class: 'mdl-navigation__link'%>
        <%#= link_to 'Essays',  essays_path, class: 'mdl-navigation__link'%>
        <%#= link_to 'Per Talks', podcasts_path, class: 'mdl-navigation__link' %>
        <%#= link_to 'Resources', '/resources', class: 'mdl-navigation__link' %>
        <br>
        <% if user_signed_in? %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--accent" %>
        <% else %>
          <%= link_to "Join Us", new_user_registration_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--accent" %>
          <%= link_to "Log In", new_user_session_path, class: "mdl-button mdl-js-button mdl-button--raised  mdl-button--colored" %>
        <% end %>
      </nav>
    </div>
    <main class="mdl-layout__content mdl-layout__container">
      <div class="page-content"><!-- Your content goes here -->
        <%= yield %>
      </div>
      <footer class="mdl-mini-footer">
        <div class="mdl-mini-footer__left-section">
          <div class="mdl-logo">The Periculum 0.1.9</div>
          <ul class="mdl-mini-footer__link-list">
            <li><%= link_to 'About', about_path%></li>
            <li><%= link_to 'Suggestions', new_contact_path%></li>
            <li><%= link_to 'Privacy', privacy_path%></li>
            <li><%= link_to 'Terms', terms_path%></li>
          </ul>
        </div>
        <div class="mdl-mini-footer__right-section">
          <ul class="mdl-mini-footer__link-list">
            <% if user_signed_in? %>
              <% if current_user.profile %>
                <li><%= link_to "Profile", user_path(id: current_user.id) %></li>
              <% else %>
                <li><%=link_to "Create profile", new_user_profile_path(user_id: current_user.id) %></li>
              <% end %>
              <li><%= link_to "Community", users_path %></li>
            <% end %>
            <li><a href="//twitter.com/thepericulum"><i class="fa fa-twitter"></i></a></li>
            <li><a href="//github.com/Bardia95/the_periculum"><i class="fa fa-github"></i></a></li>
            <li><a href="https://commerce.coinbase.com/checkout/635fb0d9-58bc-4c65-8931-a8b572b2ab44">Donate with Crypto</a></li>
          </ul>
        </div>
      </footer>
    </main>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
</html>